name: Trivy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: 19 10 * * 1

permissions:
  contents: read

jobs:
  scan:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.29.0
        with:
          scan-type: fs
          scan-ref: .
          format: table
          exit-code: 1
          vuln-type: os,library
          severity: HIGH,CRITICAL
