name: Zizmor

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  zizmor:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Run Zizmor
        uses: woodruffw/zizmor@v1.5.0
        with:
          args: .
